# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpAu8y9TxLtSx0VMmO-lkLtkl-wLF9GZ
"""



print("hello world")